#!/bin/bash

########################  FIREFOX

_echot "------- firefox profile"
_echoA "Choose the right path to create a profile & close application"
_askno "Validate to continue"
firefox --ProfileManager

_echot "------- user.js"
pth=${HOME}/.mozilla/firefox/${USER}
[ -d "${pth}" ] || _eval mkdir -p ${pth}
_eval ln -s "${_PATH_BS}/conf/user.js" ${pth}/user.js
_evalr chown ${USER}:${USER} ${pth}

########################  THUNDERBIRD

_echot "------- thunderbird profile"
_echoA "Choose the right path to create a profile & close application"
_askno "Validate to continue"
thunderbird --ProfileManager
