#!/bin/bash

_echot "------- python"
packages="python python-pip python-pipx"
_install_pcks ${packages}

packages="yt-dlp"
for package in ${packages}; do
	_echot "------- pipx"
	_eval pipx install ${package}
done

